version: '2.2'

services:
  voter:
    build:
      context: client/backend
    volumes:
     - './client/backend:/app/backend:rw'
    ports:
     - "5000:5000"
  proxy:
    build:
      context: vote_proxy/backend
    volumes:
     - './vote_proxy/backend:/app/backend:rw'
    ports:
     - "15000:5000"
  ea:
    build:
      context: election_authority/backend
    volumes:
     - './election_authority/backend:/app/backend:rw'
    ports:
     - "25000:5000"
